export enum ErrorType {
  MISSING_FIELD = 'MISSING_FIELD',
  INVALID_FORMAT = 'INVALID_FORMAT',
  DUPLICATE_QUESTION = 'DUPLICATE_QUESTION',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
